title: Hello, world! I'm Vishal Borana
description: > # this means to ignore newlines until "baseurl:"
  Hey, I'm Vishal from India. A fulltime software developer with proficieny in Python,SQL and Flutter.
  A visionary who likes to talk about ideas,animals and life in mountains.
  Lets collaborate and build something cool!  
permalink: ':title/'
baseurl: "/flexible-jekyll" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: "https://twitter.com/vish98950"#if your site has a twitter account, enter it here

# Author Settings
author: Vishal Borana # add your name
author-img: vishal_borana.png # add your photo
about-author: I am a software developer focusing on Data Science, Machine Learning and Cloud Technologies. A Life-Long learner. # add description
social-twitter: "https://twitter.com/vish98950"# add your Twitter handle
social-facebook: # add your Facebook handle
social-github: vishal2develop # add your Github handle
social-linkedin: "https://www.linkedin.com/in/vishal-borana/"# add your Linkedin handle
social-email: "vishalborana2407@gmail.com"# add your Email address

# Disqus
discus-identifier: BreakingCode # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
